on:
  push:
    branches-ignore:
      - main

permissions:
  contents: read 
  checks: write
  id-token: write
  pull-requests: write
  
jobs:
  build:
    strategy:
      fail-fast: false
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '5.1.1'

      - run: opam install . --deps-only --with-test
        working-directory: ${{ github.event.repository.name }}

      - run: opam exec -- dune build
        working-directory: ${{ github.event.repository.name }}

      - run: opam exec -- dune runtest
        working-directory: ${{ github.event.repository.name }}

      - run: opam install dune-release 
        working-directory: ${{ github.event.repository.name }}

      - run: opam exec -- dune-release lint
        working-directory: ${{ github.event.repository.name }}

