name: Builds, tests & co

on:
  push:
    branches:
      - main

permissions:
  contents: write
  
jobs:
  build:
    strategy:
      fail-fast: false
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: '5.1.1'

      - run: opam install . --deps-only --with-test

      - run: opam exec -- dune build

      - run: opam exec -- dune runtest

      - run: opam install dune-release 

      - run: opam exec -- dune-release lint

      - run: |
          git config user.email "${{ secrets.USER_EMAIL }}"
          git config user.name "Paulo Suzart"

      - run: |
          opam exec -- dune-release tag -f -y
          opam exec -- dune-release distrib
          opam exec -- dune-release publish -y --token ${{ secrets.PERSONAL_TOKEN }}
          opam exec -- dune-release opam pkg
          opam exec -- dune-release opam submit
